### ISSUE TITLE
OpenSSL issue

### ISSUE THREAD

**Issue by alexgleason** [directactioneverywhere/liberationpledge-api#1]
App doesn't run.

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/app/liberationpledge_api/server.py", line 60, in <module>
    gc = get_gspread_client()
  File "/app/liberationpledge_api/server.py", line 59, in get_gspread_client
    return gspread.authorize(credentials)
  File "/app/.heroku/python/lib/python3.5/site-packages/gspread/client.py", line 331, in authorize
    client.login()
  File "/app/.heroku/python/lib/python3.5/site-packages/gspread/client.py", line 101, in login
    self.auth.refresh(http)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 633, in refresh
    self._refresh(http.request)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 842, in _refresh
    self._do_refresh_request(http_request)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 869, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 1549, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 1677, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/_openssl_crypt.py", line 120, in from_string
    pkey = crypto.load_pkcs12(key, password).get_privatekey()
  File "/app/.heroku/python/lib/python3.5/site-packages/OpenSSL/crypto.py", line 2729, in load_pkcs12
    _raise_current_error()
  File "/app/.heroku/python/lib/python3.5/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'wrong tag'), ('asn1 encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error')]
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/app/liberationpledge_api/server.py", line 60, in <module>
    gc = get_gspread_client()
  File "/app/liberationpledge_api/server.py", line 59, in get_gspread_client
    return gspread.authorize(credentials)
  File "/app/.heroku/python/lib/python3.5/site-packages/gspread/client.py", line 331, in authorize
    client.login()
  File "/app/.heroku/python/lib/python3.5/site-packages/gspread/client.py", line 101, in login
    self.auth.refresh(http)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 633, in refresh
    self._refresh(http.request)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 842, in _refresh
    self._do_refresh_request(http_request)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 869, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 1549, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 1677, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/_openssl_crypt.py", line 120, in from_string
    pkey = crypto.load_pkcs12(key, password).get_privatekey()
  File "/app/.heroku/python/lib/python3.5/site-packages/OpenSSL/crypto.py", line 2729, in load_pkcs12
    _raise_current_error()
  File "/app/.heroku/python/lib/python3.5/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'wrong tag'), ('asn1 encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error')]
[2016-05-12 01:16:05 +0000] [148] [INFO] Worker exiting (pid: 148)
[2016-05-12 01:16:06 +0000] [9] [INFO] Shutting down: Master
[2016-05-12 01:16:06 +0000] [9] [INFO] Reason: Worker failed to boot.
```

Haven't been able to figure it out yet.

**Comment by alexgleason** [comment]
The above error is when the private key envvar is formatted without newlines.

When it's formatted _with_ newlines, the error is this instead:

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/app/liberationpledge_api/server.py", line 60, in <module>
    gc = get_gspread_client()
  File "/app/liberationpledge_api/server.py", line 59, in get_gspread_client
    return gspread.authorize(credentials)
  File "/app/.heroku/python/lib/python3.5/site-packages/gspread/client.py", line 331, in authorize
    client.login()
  File "/app/.heroku/python/lib/python3.5/site-packages/gspread/client.py", line 101, in login
    self.auth.refresh(http)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 633, in refresh
    self._refresh(http.request)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 842, in _refresh
    self._do_refresh_request(http_request)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 869, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 1549, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 1677, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/_openssl_crypt.py", line 117, in from_string
    pkey = crypto.load_privatekey(crypto.FILETYPE_PEM, parsed_pem_key)
  File "/app/.heroku/python/lib/python3.5/site-packages/OpenSSL/crypto.py", line 2483, in load_privatekey
    _raise_current_error()
  File "/app/.heroku/python/lib/python3.5/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: []
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/app/.heroku/python/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/app/liberationpledge_api/server.py", line 60, in <module>
    gc = get_gspread_client()
  File "/app/liberationpledge_api/server.py", line 59, in get_gspread_client
    return gspread.authorize(credentials)
  File "/app/.heroku/python/lib/python3.5/site-packages/gspread/client.py", line 331, in authorize
    client.login()
  File "/app/.heroku/python/lib/python3.5/site-packages/gspread/client.py", line 101, in login
    self.auth.refresh(http)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 633, in refresh
    self._refresh(http.request)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 842, in _refresh
    self._do_refresh_request(http_request)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 869, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 1549, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/client.py", line 1677, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/app/.heroku/python/lib/python3.5/site-packages/oauth2client/_openssl_crypt.py", line 117, in from_string
    pkey = crypto.load_privatekey(crypto.FILETYPE_PEM, parsed_pem_key)
  File "/app/.heroku/python/lib/python3.5/site-packages/OpenSSL/crypto.py", line 2483, in load_privatekey
    _raise_current_error()
  File "/app/.heroku/python/lib/python3.5/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: []
[2016-05-13 03:12:29 +0000] [147] [INFO] Worker exiting (pid: 147)
[2016-05-13 03:12:29 +0000] [9] [INFO] Shutting down: Master
[2016-05-13 03:12:29 +0000] [9] [INFO] Reason: Worker failed to boot.
```

**Comment by alexgleason** [comment]
Solved
